### ISSUE TITLE
Look at flaky tests and make them deterministic

### ISSUE THREAD

**Issue by MattDelac** [feast-dev/feast#1647]
## Expected Behavior 
Ideally, all the tests should be deterministic

## Current Behavior
Some tests are currently flaky which makes the development experience more painful that it could be
![image](https://user-images.githubusercontent.com/18557047/122083540-f4dccc00-cdce-11eb-929e-e9f21e4a8325.png)

## Steps to reproduce
Run integration tests and some of them might fail (don't know the frequency of the problem)

### Specifications

- Version:
- Platform:
- Subsystem:

**Comment by felixwang9817** [comment]
Flaky integration tests are caused by concurrency issues between three Python processes running the same test, which happens when an integration test creates a BigQuery table with a specific name without sufficient randomization (e.g. appending `time.time_ns()`). Importantly, appending `time.time()` is not sufficient; tests should use `time.time_ns()`.

[This PR](https://github.com/feast-dev/feast/pull/1711) gives an example of this kind of mistake and the appropriate fix.
