### ISSUE TITLE
Will removing the dependency between offlinestore and datasource be included in the roadmap?

### ISSUE THREAD

**Issue by sjkim2322** [feast-dev/feast#1820]
Through [this PR](https://github.com/feast-dev/feast/pull/1713), I can create and use additional datasources(e.g hive..) in addition to the built-in datasources(file, bigquery..).

But, The current implementation expects the use of a specific datasource in the offlinestore.

For example, [in fileOfflineStore](https://github.com/feast-dev/feast/blob/master/sdk/python/feast/infra/offline_stores/file.py#L114-L119),
```python
                ...
                # Read offline parquet data in pyarrow format.
                filesystem, path = FileSource.create_filesystem_and_path(
                    feature_view.batch_source.path,
                    feature_view.batch_source.file_options.s3_endpoint_override,
                )
                table = pyarrow.parquet.read_table(path, filesystem=filesystem)
                ...
```
The batch_source(input) of feature_view is expected to be a fileSource.

Since we can create and use custom datasources, I think we need to remove the dependency on datasources from offlinestore.
For example, the above part will be changed to below.
```python
     talbe = feature_view.batch_source.read_to_pyarrow_table()
```

Will this be included in Feast's roadmap?  or Is there something I misunderstood?

**Comment by adchia** [comment]
Is there a specific problem you're aiming to solve with this / example scenario you have in mind? 

The offline store is tied to the data source because we're using the offline store as a compute engine to query over the data source. A related version of this is to use e.g. BigQuery / RedShift to federate reads over GCS/S3, which is somewhat supported by those data sources already.
