### ISSUE TITLE
feast fraud detection example not working 

### ISSUE THREAD

**Issue by aqibfayyaz** [feast-dev/feast#2117]
i am trying to run the example **https://colab.research.google.com/github/feast-dev/feast-fraud-tutorial/blob/master/notebooks/Fraud_Detection_Tutorial.ipynb** but when i reach this block of code
**!gcloud ai-platform versions create version_3 \
--model $AI_PLATFORM_MODEL_NAME \
--runtime-version 2.2   \
--python-version 3.7 \
--framework scikit-learn \
--origin gs://$BUCKET_NAME/model_dir \
--region global**
it throws the following error
**Create Version failed. Bad model detected with error: "Failed to load model: Could not load the model: /tmp/model/0001/model.joblib. No module named 'dill'. (Error code: 0)"**
i have dill installed

**Comment by tsotnet** [comment]
I think this is because we added `dill` dependency some time ago. Importing `dill` in codebase automatically populates additional types to `pickle.Pickler.dispatch`, and I think this could be leading to the problem on the model serving side - GCP's AI Platform does not have `dill` in their runtime, so it can't deserialize the object.

Can you try calling this before you train & serialize your model again?
```
import dill
dill.extend(use_dill=False)
```
Please let me know if the same gcloud CLI call works after that.

**Comment by aqibfayyaz** [comment]
@tsotnet Great it is working now!!.
