### ISSUE TITLE
Snowflake offline store, feature inference doesn't work for VARCHAR types.

### ISSUE THREAD

**Issue by tonyqiu2020** [feast-dev/feast#2412]
## Expected Behavior 

When using Snowflake offline store, feature inference should consider VARCHAR columns in snowflake as str. 

## Current Behavior

When using Snowflake offline store, feature inference considers VARCHAR type columns in snowflake as object in pandas dataframe, and therefore cause UNKNOWN error. 

https://github.com/feast-dev/feast/blob/master/sdk/python/feast/infra/offline_stores/snowflake_source.py#L196-L207
https://github.com/feast-dev/feast/blob/98b8d8da7e8e717ec93197f253368551951ca675/sdk/python/feast/type_map.py#L532

### Specifications

- Version: 0.18.0+
- Platform: mac os
- Subsystem:

## Possible Solution

I would suggest changing ValueType.UNKNOWN to ValueType.STRING since pandas dtype object is str or mixed. And typically we just need it as string

https://github.com/feast-dev/feast/blob/master/sdk/python/feast/type_map.py#L532

**Comment by kevjumba** [comment]
Hi Tony! Can you add a specific example of this not working? Have you encountered this because the way feature inference works is we capture the columns of a snowflake table and convert it to pandas dataframe as a single row. 
The snowflake documentation states here very clearly that a VARCHAR datatype converts to `str` which is handled by the type map as a `ValueType.STRING`.
https://docs.snowflake.com/en/user-guide/python-connector-pandas.html

Also string datatypes in Snowflake have been working for Feast in the past.

**Comment by tonyqiu2020** [comment]
I think it is general any varchar or str in snowflake
```
create table test_table (
  name varchar (100),  -- variable string column
  preferences string, -- column used to store JSON type of data
  created_at timestamp
  )

insert into test_table
values ( 'test', 'str_test', '2020-04-04 16:57:53.653');
```

And if we run code like this part
https://github.com/feast-dev/feast/blob/master/sdk/python/feast/infra/offline_stores/snowflake_source.py#L196-L207

I got [('NAME', 'object'), ('PREFERENCES', 'object'), ('CREATED_AT', 'datetime64[ns]')]

**Comment by felixwang9817** [comment]
@tonyqiu2020 pretty sure #2558 resolves this! Feel free to reopen if I'm mistaken.
