### ISSUE TITLE
SnowflakeOfflineStoreConfig import fails in the python feature server

### ISSUE THREAD

**Issue by jerive** [feast-dev/feast#2560]
## Expected Behavior 
Configuring snowflake does not make the AWS python server fail

## Current Behavior
```
[ERROR] FeastModuleImportError: Could not import module 'feast.infra.offline_stores.snowflake' 
while attempting to load class 'SnowflakeOfflineStoreConfig'
```

## Steps to reproduce
- Configure a snowflake offline store
- Deploy the AWS python feature server
- Query /get-online-features
### Specifications

- Version: v0.20.0
- Platform: 
- Subsystem: Python feature server AWS

**Comment by achals** [comment]
Hi @jerive , you're right that this is indeed a bug. We're planning on fixing this in a patch release soon (hopefully this week)

**Comment by achals** [comment]
More context: The [AWS Feature Server dockerfile](https://github.com/feast-dev/feast/blob/master/sdk/python/feast/infra/feature_servers/aws_lambda/Dockerfile) doesn't install the `snowflake` extra, and feast by design eagerly loads the offline store. 

Ideally, we should instantiate the offline store lazily so that we don't load it in environments like feature serving, where it's not neeeded.
