### ISSUE TITLE
Accept List along with Dict for tags

### ISSUE THREAD

**Issue by tkch3n** [feast-dev/feast#2813]
**Is your feature request related to a problem? Please describe.**
Feast objects may be shared across projects/use cases. Currently, tags are `Dict[str, str]` so we cannot specify multiple values for a key like `project`. 

**Describe the solution you'd like**
Accept list as a tag value (`Dict[str, List[str]]`).

**Describe alternatives you've considered**

**Additional context**

**Comment by achals** [comment]
I think this would be a cool feature to have!

**Comment by amommendes** [comment]
Hey @achals , is this still important?

I was thinking about the best way to solve this:
- Changing protos in order to have a more complex type for tags (with strings or list values) and update to_proto and from_proto methods
- Join each dict value when this is a `list` in order to always serialize as a `string`
- In both ways we could create a class `Tags` in order to avoid repetition of these handlings in feature_views, field, and feature objects 


WDYT?
