### ISSUE TITLE
Upgrade protobuf past version 4

### ISSUE THREAD

**Issue by chhabrakadabra** [feast-dev/feast#3101]
**Is your feature request related to a problem? Please describe.**

Feast pins protobuf to `<4`. This means that for M1 Apple machines, we have to employ some hacks. It would be nice to not have to do that. Also maintaining an upper bound on a popular library means that installing Feast alongside other libraries involves friction.

**Describe the solution you'd like**

Ideally, we remove the upper bound for protobuf in `setup.py`. It seems like the breaking changes are pretty minor: https://developers.google.com/protocol-buffers/docs/news/2022-05-06#python-updates

**Describe alternatives you've considered**

N/A

**Comment by kevjumba** [comment]
hey @chhabrakadabra, this is actually not possible as of now since we have 2 packages(tensorflow-metadata) and grpcio that have their own caps for under protobuf version 4. I am going to relax the protobuf dependency for now but the version will not rise above 4 due to these packages.

Both grpcio-tools and tensorflow-metadata are the latest version so there's nothing we can really do until they update their dependencies.
