### ISSUE TITLE
How data versioning works in FEAST

### ISSUE THREAD

**Issue by PrhldK** [feast-dev/feast#3112]
Problem: How data versioning works in FEAST?

I know how feature/feature set versioning works.
Just like  I have a new code recomputing the value of a previously computed feature. I would like to know the history & from where this change is coming.
 I can track what value was earlier. means like a versioning of value.
Compare and check.
If any blogs/tutorials/git link are available. It will be usefule.

**Comment by kevjumba** [comment]
For features set versioning, we generally promote using a version control repository like git to manage your feature changes. As for value tracking, Feast currently doesn't support any type of previous value tracking. We store all of the metadata about your features in a registry and any changes to the registry will overwrite the previous values. A possible way of doing this version tracking is to create a new feast repository in a new version with a new registry.

**Comment by PrhldK** [comment]
@kevjumba  Thanks for the update.  
for the git, do you know if the git is automatically stored with Feast?

**Comment by NhuanTDBK** [comment]
@PrhldK  You can use DeltaLake format to achieve data versioning

**Comment by amithadiraju1694** [comment]
Great question @PrhldK  I'm also interested in the same topic. It is not clear from Feasts' documentation on:

1) How ( or If ) Feast versions any of our meta data or data; I understand that FeatureService versions the data. But exactly what is in that version ?

2) Any example of FeatureService , interms of getting data of the past ( like v1 instead of current version ? ).

3) Where does that v1, v2 etc gets stored ? Registry ?

4) What happens to these versions, if underlying source tables are dropped ?

Really appreciate help here !!

**Comment by amithadiraju1694** [comment]
> @NhuanTDBK  Using DeltaLake for data versioning makes sense. But I'm little confused on what "versioning" does a feature store do in general , or may be Feast ? Does Feast do anything by default ? Or the dev needs to do something on their own ?

Is Feature Service the only "versioning" mechanism Feast provides ? Any inputs will be much appreciated.
