### ISSUE TITLE
Support requested features on Postgresql online store

### ISSUE THREAD

**Issue by NhuanTDBK** [feast-dev/feast#3173]
**Is your feature request related to a problem? Please describe.**
As a user, I want to retrieve subset of features on Postgresql online store instead of fetching all features

**Describe the solution you'd like**
Update online_read method to retrieve subset of features

**Additional context**
I'm close to creating a pull request for this issue myself.

**Comment by felixwang9817** [comment]
hey @NhuanTDBK, are you sure that Postgres currently doesn't support retrieving a subset of features?

I took a quick look at #3203 and I noticed that the sqlite online store `online_read` method also does not make use of `requested_features`; that is because later on the requested features are correctly subselected in `FeatureStore._read_from_online_store` [here](https://github.com/feast-dev/feast/blob/master/sdk/python/feast/feature_store.py#L2024)

I would be surprised if this didn't also work for Postgres

**Comment by NhuanTDBK** [comment]
@felixwang9817  I think it's more efficient when it pushed down predicates to Postgres instead of fetching all features and filter out in the client side (For this case, we want to build the AutoFeatureSelection module to automatically select the best features from thousand of features)

**Comment by felixwang9817** [comment]
@NhuanTDBK sorry for the slow response here - that makes sense to me, I'll stamp your PR!
