### ISSUE TITLE
Test loading S3 parquet folder in dataset format

### ISSUE THREAD

**Issue by mzwiessele** [feast-dev/feast#3235]
Test that a parquet dataset saved in dataset format can be loaded and accessed using `get_historical_features`.

Steps:

- upload a parquet dataset to the test s3 folder
- point a source to the parquet dataset s3 folder (**not the file**)
- load the source features using `get_historical_features`

> Ideally, there'd be a test for this running, but you'd be blocked on making a file within the Feast integration tests S3 bucket. Mind making an issue for that separately? @mzwiessele

_Originally posted by @adchia in https://github.com/feast-dev/feast/issues/3217#issuecomment-1249562980_

**Comment by felixwang9817** [comment]
I think there are probably two ways to do this:
* there is an `S3FileDataSourceCreator` in `sdk/python/tests/integration/universal/feature_repos/universal/data_sources/file.py`, which uses `minio` - it hasn't been used in a while, but it could be updated and used
* instead of using `minio`, we could also just create a dataset and upload data directly to an `S3` bucket - we could just use the `feast-integration-tests` S3 bucket, which is used in `universal/data_sources/redshift.py`
