### ISSUE TITLE
When configuring using 'FileSource', how do I add a file with new data to reflect it?

### ISSUE THREAD

**Issue by sungreong** [feast-dev/feast#3298]
I want to configure the feature store with an existing file and reflect it in the feature store when a new file is added.

I'm looking at several examples, but I can't find any of these examples.

I have a few questions regarding this.

1. When a new file is added, how do I add a new file while retaining the data of the existing file?

2. If question 1 is impossible, how can we add new data to the online store for new files?

Thank you for making a good library, and I look forward to a good answer.

![image](https://user-images.githubusercontent.com/22166391/196418402-e8b50091-b6b2-484f-bde5-d9921e5cb0bc.png)

**Comment by achals** [comment]
Hey @sungreong, this is a good question - the real answer is that this use case isn't really supported, since the file offline store is meant just for dev environments/getting started with Feast. For production, we generally recommend using one of the [other supported offline stores](https://docs.feast.dev/reference/offline-stores), which support your use case.
