### ISSUE TITLE
Redis: alternate data model keying by entity + FV

### ISSUE THREAD

**Issue by adchia** [feast-dev/feast#3338]
Right now Feast with Redis maps entities -> features in Redis.

One interesting alternative might be to introduce a different option for the data model:
- map from (entity + FV) -> feature value

This would then enable Feast to:
- always run HGETALL for feature views if the user selects the entire feature view in a feature service.
- have the ability to expire in Redis on a more fine grained level (instead of expiring whole entities at a time)

**Comment by Spartee** [comment]
@adchia This is interesting, I'd be curious to see how this affects performance. The expiration piece is a very nice effect of this.

One aspect we've been looking at is how to enable the use of other Redis data structures alongside Feast. For ex. Feast supplying vector embedding features to use with the search functionality. 

This would require values to be stored as bytes instead of protobuf. The top level key, hash key, and timestamp info could still be protobuf, but the value would have to be a bytes.

i.e. 

```python 
import numpy as np

array = np.array([1,2,3], dtype=np.float32).asbytes()
```

but if the data model was switched to the one you suggest above, this could be other data type supported by feast... I assume? 

There would be some impact to storage (protobuf would be smaller packets because of binary), but this would enable other redis features when redis is used as the online store.

The other option would also be JSON as that is supported as well. 

bit of a brain dump, but curious to hear your thoughts.
