### ISSUE TITLE
Revert support for python 3.8 

### ISSUE THREAD

**Issue by ElliotNguyen68** [feast-dev/feast#4073]
Hi maintainer team, I currently using feast, but today when I tried to use lastest version on github repo, I found that feast no longer support 3.8 python, due to this pr https://github.com/feast-dev/feast/pull/4010. I wonder why we drop python 3.8 and just now support python >=3.9 ?

**Comment by tokoko** [comment]
I think this was discussed on community calls a while back, see [Jeremy's comment](https://github.com/feast-dev/feast/pull/3985#issuecomment-1981528352). Regardless, revert to 3.8 is practically impossible now, too many dependencies were already updated to versions with no support for 3.8. just curious, do you have a hard requirement for 3.8?

**Comment by ElliotNguyen68** [comment]
Yes currently our team is using python 3.8 for development and production, using 3rd party service so it is not easy to change python version, so adding hard requirement in os to run from python3.9 and above is somethings will totally stop our team to using upcomming version of feast. @tokoko

**Comment by tokoko** [comment]
Been in that boat myself before, tied to a specific spark version because of a hadoop distro. Forgive me for unsolicited advice, judging from your PRs you are primarily using it with spark, right? Have you tried packaging the whole python environment like [this](https://spark.apache.org/docs/latest/api/python/user_guide/python_packaging.html#using-conda) with conda?

Alternatively, you can try building the latest source code from master yourself. you will probably have to make some changes, but the chances are parts of the codebase you care about still works with 3.8.

**Comment by ElliotNguyen68** [comment]
Yes you are correct, I primarily use feast with spark, but now I am even not able to install feast with python3.8 when pip install,  not reach spark part yet @tokoko.

**Comment by jeremyary** [comment]
Thanks for opening the issue, but unfortunately, reverting to include support for 3.8 isn't feasible for a few reasons. We didn't take the choice lightly or without a good amount of deliberation amongst devs and community members. v3.8 is nearing extended support EOL (including security updates), so sunsetting of that version has commenced for some of our dependencies meaning we either come along for the update ride, start stripping out core pieces of Feast or develop a means for bundling ourselves. Even with dependencies aside, given where v3.8 is in lifecycle, the first option makes the most sense for us from a security perspective as well.
