### ISSUE TITLE
S3 doesn't work if AWS metadata is blocked on kubernetes.

### ISSUE THREAD

**Issue by empath-nirvana** [feast-dev/feast#4122]
## Expected Behavior 
This is the issue I'm experiencing, but the issue is closed and the problem still exists in the latest version.

https://github.com/feast-dev/feast/issues/3492

It should be able to pull the region and anything else it needs from well known environment variables, but it doesn't. (I have AWS_REGION set as an environment variable and it doesn't work, for example)

## Steps to reproduce

Configure as mentioned in the ticket, but with aws metadata blocked on the node.

### Specifications

- Version:
- Platform: eks
- Subsystem:

## Possible Solution

Initialize the s3 client in a way that it will use well known aws environment variables like AWS_REGION if metadata isn't available.

**Comment by tokoko** [comment]
Thanks for the issue. actually, the problem here is that feast treats [awsRegion](https://github.com/feast-dev/feast/blob/master/java/serving/src/main/java/feast/serving/service/config/RegistryConfigModule.java#L45) config as mandatory. This shouldn't be affecting any other aws env varieble. Just a note that what you can do before an actual fix is to provide region in the configuration like this:
```
registry: s3://example_feast_registry
awsRegion: eu-central-1
```
