### ISSUE TITLE
Support easier feature serving and model serving with KServe

### ISSUE THREAD

**Issue by franciscojavierarceo** [feast-dev/feast#4139]
**Is your feature request related to a problem? Please describe.**
At the moment, Model serving (via KServe) and Feature Serving (via Feast—the Feature Store) are separate components without any guidance on how to best serve production machine learning features and models.

It would be beneficial to the community to outline (or support) how these two components could best fit together so that users could launch production machine learning applications with a better understanding about best practices. At the moment, this is outlined by KServe but the approach has some limitations [1]. It would be beneficial to offer some form of integration that outlines how users could launch these two services in a way that maximizes the strengths of each component.

[1] The limitations will be discussed more thoroughly in the RFC but [their approach](https://kserve.github.io/website/0.7/modelserving/v1beta1/transformer/feast/#run-a-prediction) is to treat the online feature store as a Transformer.

**Describe the solution you'd like**
 I will be drafting a proposal in [this document](https://docs.google.com/document/d/1PzBbTs_8R73XhuDq3CO0slmGy5S_ci2rwtbx1L-Ukqc/edit#heading=h.9gaqqtox9jg6).

**Describe alternatives you've considered**
There are pros and cons to different approaches and I would like to solicit feedback from the community to understand what would result in the best tradeoffs.

**Additional context**

- [Sagemaker's high level feature store and inference diagram](https://aws.amazon.com/sagemaker/feature-store/)
![image](https://github.com/kubeflow/kubeflow/assets/4163062/94803b1a-b5c2-4209-b989-84970b4b53c8)

- [Databrick's high level feature store and inference diagram](https://docs.databricks.com/en/machine-learning/feature-store/index.html#how-does-databricks-feature-store-work)

![image](https://github.com/kubeflow/kubeflow/assets/4163062/b6a0baa0-f0c7-4b3c-8067-8320f71f35c5)

- [Tecton's high level feature store and inference diagram](https://www.tecton.ai/blog/what-is-a-feature-store/)
![Screenshot 2024-04-23 at 12 05 15 PM](https://github.com/kubeflow/kubeflow/assets/4163062/c2376bae-5ccc-482a-ad8c-d125a14d9dd1)

https://github.com/kubeflow/kubeflow/issues/7564

**Comment by tokoko** [comment]
@franciscojavierarceo thanks for kickstarting this. As I said on the call, I have some concrete ideas about changes in feast that could make this possible, but before we go there, let me say a couple of things about the differences between the approaches (preprocessor vs transformer, if I'm getting it right). Although I probably lean towards your point of view, I don't really think we can recommend either approach. The way I think about it, the approach taken usually depends on the user's existing ml serving practices and infrastructure. 1) When infra mostly consists of one-off independent model services, it makes sense to simply add another layer in front that will take care of feature store communication. 2) Alternatively if you're already heavily invested into a web of composable transformers and models depending on other models (kserve, seldon and so on) it makes a lot of sense to treat it as just another transformer. I think we should try to create a toolbox in feast that would apply to both scenarios.

**Comment by franciscojavierarceo** [comment]
I'm not particularly familiar with the second scenario you outlined but I do agree that Feast should be a toolbox that could support both scenarios. That said, and given my previous experience, I'm going to focus my contributions to the RFC on case (1) since it is not outlined today and it is the one I've encountered the most frequently (and my suspicion is that it's the most common pattern most practicioners actually need).

**Comment by tokoko** [comment]
sure, I'm right there with you, that's my experience as well. another point is that I think we should aim to integrate with [open inference protocol](https://github.com/kserve/open-inference-protocol) rather than any particular inference server. my understanding is that it's based on kserve v2 protocol and closest to the industry standard that there is. it's also pretty well-defined (both http and grpc) with a number of client implementations we could use, triton has good set of http and grpc python clients for it for example.

**Comment by tokoko** [comment]
@franciscojavierarceo I have been working on this internally and came up with some draft middleware implementation. Let me know if you're thinking along those lines as well.

For simpler model deployments (without model mesh) we should have a way for users to deploy a middleware service that wraps both feast and actual model server. I think we can make the assumption that model server needs to be OIP-compatible and we can go a step further and make our own middleware expose OIP interface as well. The difference will be that OIP model server will expect actual features as inputs and our middleware will only expect entity values and required request features (if any). Here's my very detailed [uml](https://www.plantuml.com/plantuml/svg/XL91QWCn3BplAqHEMKW_i8UI7bh8eRIq3p1cLoa2HpQsKjhVrnktnSOAEHZR8yre97kVn4OvdzmGyaup1Si23o4ucgsGvmP__1ACRDspNz2zO_p423R1HiEtBuVNSTFGdz3AEM99Q29lk51ga0FhfGgkbXegst1thxgTWFYuKf25vDlGCWvQNgOtRYVuG36U7J6QOuaasFwUJCf9DECEAjcQlmgM9Yz2bK95kCIxohsEudU2FqMJL_2Sy5fRoW3xeUp-zSP18LnrSLelDorKxzHHziXB_eu_) for it :).  Making middleware server expose OIP will also simplify using it for clients as there will be no need for them to use feast and can employ standard protocols or already existing client libraries for them (`tritonclient` is the best one for OIP, i think).

For the python version, we can even base own server on existing frameworks, mlserver has a very easy way of implementing [custom OIP services](https://developer.ibm.com/tutorials/awb-creating-custom-runtimes-in-modelmesh/#implement-the-mlmodel-class) without worrying too much about the actual server plumbing.

Another point to note here is that users will be able to make these services part of the kserve (or probably seldon as well) model mesh, but i don't know if that's such a good idea. As we will be doing an oip call to the underlying model server ourselves from the middleware instead of relying on the mesh to do it for us, the mesh itself won't be able to track that bit of communication.

**Comment by franciscojavierarceo** [comment]
Awesome! I'll review this in more detail later. Do you want to collaborate on the doc? Feel free to add your name and suggest some changes.

**Comment by franciscojavierarceo** [comment]
Let's discuss more in the doc. I think what you're calling out completely makes sense.

I think exposing an OIP makes sense, the only detail being that (as I outlined in my doc) sometimes users will want to retrieve just features or (in the future) retrieve features as inference is being generated (to be discussed more later probably).

**Comment by tokoko** [comment]
I started the solution section, please look through it when you get the chance, especially the part at the end under //TODO.

**Comment by franciscojavierarceo** [comment]
The MLServer/Seldon seems really promising, as it supports PyTorch, Tensorflow, and XGBoost...

**Comment by tokoko** [comment]
One problem there right now is that they are on `pydantic<2` (we are on `pydantic>2`) so can't add to the project yet. They are planning an upgrade in the next release.

**Comment by shuchu** [comment]
We may need to cautious about selecting SeldonIO or other third parities. The enterprise users may prefer open source project that has minimum legal requirements/issue to themselves. Kubeflow or Kserve is a very popular one than SeldonIO. And in kubeflow's document, it also mentions Feast as an Add-on.

**Comment by shuchu** [comment]
https://www.kubeflow.org/docs/external-add-ons/feature-store/

**Comment by tokoko** [comment]
@shuchu MLServer is an open source project (and kserve supports deploying it as well afaik). You should probably take a look at the proposal so far, I'm only advocating for using MLServer (Apache 2.0) and tritonclient (BSD-3) as utilitiies that would help us build an server exposing oip interface.

As to the integration with the model server, I agree. I think we shouldn't have an integration that's coupled with either one of them. We should have a vendor-neutral integration with an abstract OIP model server, which the users can deploy and manage with both kserve and seldon.

**Comment by shuchu** [comment]
Thank you, @tokoko . I take back what I said before. I agree with you that it's better for us to keep Feast in a neutral way.

Recently, I work on Kubeflow for other purposes. It seems the doc about Feast is quite old on Kubeflow's website. Let me see if I can update it. I will let you and @franciscojavierarceo know what's the situation.

**Comment by franciscojavierarceo** [comment]
I updated the documentation to outline this. Closing this out.
